# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
# https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
# <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
# option. This file may not be copied, modified, or distributed
# except according to those terms.

[package]
name = "autocxx-mdbook-preprocessor"
version = "0.30.0"
authors = ["adetaylor <adetaylor@chromium.org>", "Vladimir Pankratov <sollex.uz@gmail.com>"]
edition = "2021"
# Holds no crates.io name, and would have one created for it by a publish
# which took the workspace rather than a named set.
publish = false

[dependencies]
clap = { version = "4", features = ["cargo"] }
serde_json = "1"
itertools = "0.15"
anyhow = "1"
regex = "1"
autocxx-integration-tests = { path = "../../integration-tests", version = "=0.30.0" }
rayon = "1.5"
gag = "1.0"
env_logger = "0.11"
quote = "1"
mdbook-preprocessor = "0.5"

[dependencies.syn]
version = "3"
features = ["parsing", "full"]

[dependencies.proc-macro2]
version = "1.0.11"
features = ["span-locations"]
