// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

mod analysis;
mod api;
mod apivec;
mod codegen_cpp;
mod codegen_rs;
#[cfg(test)]
mod conversion_tests;
mod convert_error;
mod derives;
mod doc_attr;
mod error_reporter;
mod parse;
mod type_helpers;
mod utilities;

pub(crate) use super::parse_callbacks::CppOriginalName;
use crate::vendored_bindgen::callbacks::Visibility as CppVisibility;
use analysis::fun::FnAnalyzer;
use autocxx_parser::IncludeCppConfig;
pub(crate) use codegen_cpp::CppCodeGenerator;
pub(crate) use convert_error::ConvertError;
use convert_error::{ConvertErrorFromCpp, ConvertErrorWithContext, ErrorContext};
use indexmap::map::IndexMap as HashMap;
use indexmap::set::IndexSet as HashSet;
use itertools::Itertools;
use syn::{Item, ItemMod};

use crate::{
    types::{is_std_function, QualifiedName},
    CodegenOptions, CppFilePair, ParseCallbackResults, UnsafePolicy,
};

use self::{
    analysis::{
        abstract_types::{discard_ignored_functions, mark_types_abstract},
        allocators::create_alloc_and_frees,
        bridge_type_names::BridgeTypeNames,
        casts::add_casts,
        check_names,
        constructor_deps::decorate_types_with_constructor_deps,
        destructibility::remove_ownership_of_non_destructible_types,
        field_accessors::add_field_accessors,
        fun::FnPhase,
        gc::filter_apis_by_following_edges_from_allowlist,
        pod::analyze_pod_apis,
        remove_ignored::filter_apis_by_ignored_dependents,
        replace_hopeless_typedef_targets,
        statics::expose_statics,
        tdef::convert_typedef_targets,
    },
    api::{AnalysisPhase, Api, NestedCppNames, NullPhase},
    apivec::ApiVec,
    codegen_rs::RsCodeGenerator,
    parse::{find_shadowed_types, ParseBindgen},
};

const LOG_APIS: bool = true;

/// Converts the bindings generated by bindgen into a form suitable
/// for use with `cxx`.
/// In fact, most of the actual operation happens within an
/// individual `BridgeConversion`.
///
/// # Flexibility in handling bindgen output
///
/// autocxx is inevitably tied to the details of the bindgen output;
/// e.g. the creation of a 'root' mod when namespaces are enabled.
/// At the moment this crate takes the view that it's OK to panic
/// if the bindgen output is not as expected. It may be in future that
/// we need to be a bit more graceful, but for now, that's OK.
pub(crate) struct BridgeConverter<'a> {
    include_list: &'a [String],
    config: &'a IncludeCppConfig,
}

/// C++ and Rust code generation output.
pub(crate) struct CodegenResults {
    pub(crate) rs: Vec<Item>,
    pub(crate) cpp: Option<CppFilePair>,
    pub(crate) cxxgen_header_name: String,
}

impl<'a> BridgeConverter<'a> {
    pub fn new(include_list: &'a [String], config: &'a IncludeCppConfig) -> Self {
        Self {
            include_list,
            config,
        }
    }

    fn dump_apis<T: AnalysisPhase>(label: &str, apis: &ApiVec<T>) {
        if LOG_APIS {
            log::info!(
                "##### APIs after {}:\n{}",
                label,
                apis.iter()
                    .map(|api| { format!("  {api:?}") })
                    .sorted()
                    .join("\n")
            )
        }
    }

    /// Convert a TokenStream of bindgen-generated bindings to a form
    /// suitable for cxx.
    ///
    /// This is really the heart of autocxx. It parses the output of `bindgen`
    /// (although really by "parse" we mean to interpret the structures already built
    /// up by the `syn` crate).
    pub(crate) fn convert(
        &self,
        bindgen_mod: ItemMod,
        parse_callback_results: ParseCallbackResults,
        unsafe_policy: UnsafePolicy,
        inclusions: String,
        codegen_options: &CodegenOptions,
        source_file_contents: &str,
    ) -> Result<CodegenResults, ConvertError> {
        match &bindgen_mod.content {
            None => Err(ConvertError::NoContent),
            Some((_, items)) => {
                // Note which type names C++ won't look up unqualified because a
                // variable or function of the same name hides them. This has to
                // happen before parsing, which discards the hiding declaration.
                let shadowed_types = find_shadowed_types(items);
                // Parse the bindgen mod.
                let parser = ParseBindgen::new(self.config, &parse_callback_results);
                let apis = parser.parse_items(items, source_file_contents)?;
                Self::dump_apis("parsing", &apis);
                // Note which names bindgen defined more than once, while the
                // parse phase still records why each item was discarded. Later
                // analysis and garbage collection drop that context, but the
                // Rust codegen needs it to repair the bindgen mod.
                let names_duplicated_by_bindgen = find_names_duplicated_by_bindgen(&apis);
                let parse_observations = ParseObservations {
                    shadowed_types,
                    names_duplicated_by_bindgen,
                };
                // Inside parse_results, we now have a list of APIs.
                // We now enter various analysis phases.
                // First, convert any typedefs.
                // "Convert" means replacing bindgen-style type targets
                // (e.g. root::std::unique_ptr) with cxx-style targets (e.g. UniquePtr).
                let apis = convert_typedef_targets(self.config, apis, &parse_callback_results);
                Self::dump_apis("typedefs", &apis);
                // Now analyze which of them can be POD (i.e. trivial, movable, pass-by-value
                // versus which need to be opaque).
                // Specifically, let's confirm that the items requested by the user to be
                // POD really are POD, and duly mark any dependent types.
                // This returns a new list of `Api`s, which will be parameterized with
                // the analysis results.
                let analyzed_apis = analyze_pod_apis(apis, self.config, &parse_callback_results)
                    .map_err(ConvertError::Cpp)?;
                Self::dump_apis("pod analysis", &analyzed_apis);
                // A variable can only be re-exported if its type is one which
                // we expose exactly as bindgen declared it, which we only know
                // once POD analysis is complete; anything else gets a getter
                // instead, and the holder its getter hands back.
                let analyzed_apis = expose_statics(analyzed_apis);
                Self::dump_apis("static data", &analyzed_apis);
                let analyzed_apis = replace_hopeless_typedef_targets(self.config, analyzed_apis);
                let analyzed_apis = add_casts(analyzed_apis);
                let analyzed_apis =
                    add_field_accessors(analyzed_apis, self.config, &parse_callback_results);
                let analyzed_apis = create_alloc_and_frees(analyzed_apis, self.config);
                // Next, figure out how we materialize different functions.
                // Some will be simple entries in the cxx::bridge module; others will
                // require C++ wrapper functions. This is probably the most complex
                // part of `autocxx`. Again, this returns a new set of `Api`s, but
                // parameterized by a richer set of metadata.
                Self::dump_apis("adding casts", &analyzed_apis);
                let analyzed_apis = FnAnalyzer::analyze_functions(
                    analyzed_apis,
                    &unsafe_policy,
                    self.config,
                    &parse_callback_results,
                    codegen_options.force_wrapper_gen,
                );
                // If any of those functions turned out to be pure virtual, don't attempt
                // to generate UniquePtr implementations for the type, since it can't
                // be instantiated.
                Self::dump_apis("analyze fns", &analyzed_apis);
                let analyzed_apis = mark_types_abstract(analyzed_apis);
                Self::dump_apis("marking abstract", &analyzed_apis);
                // Similarly, if a type's destructor turned out to be
                // inaccessible, Rust must never own one, so withdraw the
                // constructors and allocators which would let it.
                // See google/autocxx#829.
                let analyzed_apis = remove_ownership_of_non_destructible_types(analyzed_apis);
                Self::dump_apis(
                    "removing ownership of non-destructible types",
                    &analyzed_apis,
                );
                // Annotate structs with a note of any copy/move constructors which
                // we may want to retain to avoid garbage collecting them later.
                let analyzed_apis = decorate_types_with_constructor_deps(analyzed_apis);
                Self::dump_apis("adding constructor deps", &analyzed_apis);
                let analyzed_apis = discard_ignored_functions(analyzed_apis);
                Self::dump_apis("ignoring ignorable fns", &analyzed_apis);
                // Remove any APIs whose names are not compatible with cxx, and
                // settle on the name each type goes by within the bridge mod.
                let (analyzed_apis, bridge_type_names) = check_names(analyzed_apis);
                // During parsing or subsequent processing we might have encountered
                // items which we couldn't process due to as-yet-unsupported features.
                // There might be other items depending on such things. Let's remove them
                // too.
                let analyzed_apis = filter_apis_by_ignored_dependents(analyzed_apis);
                Self::dump_apis("removing ignored dependents", &analyzed_apis);

                // We now garbage collect the ones we don't need...
                let mut analyzed_apis =
                    filter_apis_by_following_edges_from_allowlist(analyzed_apis, self.config);
                // Determine what variably-sized C types (e.g. int) we need to include
                analysis::ctypes::append_ctype_information(&mut analyzed_apis);
                Self::dump_apis("GC", &analyzed_apis);
                // The parse phase confirmed that each explicitly requested item
                // was present in the bindgen output, but the analysis phases above
                // may since have discarded some of them (usually turning them into
                // an `Api::IgnoredItem`, which yields nothing but a documentation
                // stub). Check again now that all analysis is complete, so that an
                // explicit `generate!` which produced nothing usable is a hard
                // error instead of a silent failure. See google/autocxx#1269.
                confirm_all_generate_directives_still_obeyed(self.config, &analyzed_apis)
                    .map_err(ConvertError::Cpp)?;
                // `derive!` names a type the same way, and equally may name
                // one which never made it this far - or one whose Rust
                // definition the user never sees. Settle that here too, where
                // there is still somewhere to report it.
                let derive_requests =
                    derives::resolve_derive_directives(self.config, &analyzed_apis)
                        .map_err(ConvertError::Cpp)?;
                // And finally pass them to the code gen phases, which outputs
                // code suitable for cxx to consume.
                let cxxgen_header_name = codegen_options
                    .cpp_codegen_options
                    .cxxgen_header_namer
                    .name_header();
                let cpp = CppCodeGenerator::generate_cpp_code(
                    inclusions,
                    &analyzed_apis,
                    self.config,
                    &codegen_options.cpp_codegen_options,
                    &cxxgen_header_name,
                    &parse_observations.shadowed_types,
                )
                .map_err(ConvertError::Cpp)?;
                let rs = RsCodeGenerator::generate_rs_code(
                    analyzed_apis,
                    &unsafe_policy,
                    self.include_list,
                    bindgen_mod,
                    self.config,
                    cpp.as_ref().map(|file_pair| file_pair.header_name.clone()),
                    &RsCodegenInputs {
                        parse_observations: &parse_observations,
                        bridge_type_names: &bridge_type_names,
                        derive_requests: &derive_requests,
                    },
                );
                Ok(CodegenResults {
                    rs,
                    cpp,
                    cxxgen_header_name,
                })
            }
        }
    }
}

/// Things which can only be observed around the time bindgen's output is
/// parsed, but which the code generators still need. The later analysis phases
/// and the garbage collector discard the items these are derived from, so they
/// have to be gathered up front and carried along.
pub(crate) struct ParseObservations {
    /// The type names C++ won't look up unqualified because a variable or
    /// function of the same name hides them, per [`find_shadowed_types`].
    pub(crate) shadowed_types: HashSet<QualifiedName>,
    /// The names bindgen defined more than once, per
    /// [`find_names_duplicated_by_bindgen`].
    pub(crate) names_duplicated_by_bindgen: HashSet<QualifiedName>,
}

/// What the Rust code generator needs to know beyond the `Api`s themselves.
pub(crate) struct RsCodegenInputs<'a> {
    /// See [`ParseObservations`].
    pub(crate) parse_observations: &'a ParseObservations,
    /// See [`BridgeTypeNames`].
    pub(crate) bridge_type_names: &'a BridgeTypeNames,
    /// The traits each type's `derive!` directives asked for. See
    /// [`derives::resolve_derive_directives`].
    pub(crate) derive_requests: &'a derives::DeriveRequests,
}

/// The names which bindgen defined more than once, and which `ApiVec` therefore
/// reduced to a single [`Api::IgnoredItem`].
///
/// Such a name is unusable by construction: nothing depending on it can be
/// generated, so any reference to it left in the bindgen mod is debris. That is
/// what lets Rust codegen repair the (uncompilable) mod by collapsing the
/// definitions together. A name which merely *looks* duplicated in the emitted
/// mod does not qualify - one of the definitions may be a live item that the
/// parse phase simply skipped - which is why this set is gathered here rather
/// than inferred from the bindgen output later on.
fn find_names_duplicated_by_bindgen(apis: &ApiVec<NullPhase>) -> HashSet<QualifiedName> {
    apis.iter()
        .filter_map(|api| match api {
            Api::IgnoredItem {
                name,
                err: ConvertErrorFromCpp::DuplicateItemsFoundInParsing,
                ..
            } => Some(name.name.clone()),
            _ => None,
        })
        .collect()
}

/// Newtype wrapper for a C++ "effective name", i.e. the name we'll use
/// when generating C++ code.
/// This name may contain several segments if it's an inner type,
/// e.g.
/// ```cpp
/// struct Outer {
///   struct Inner {
///   }
/// }
/// ```
/// As with [`CppOriginalName`], each constructor here is named for where its
/// string comes from, so that no Rust identifier becomes a C++ name without
/// something having said why it may. The sources are: a name bindgen reported
/// ([`CppOriginalName::to_effective_name`], and [`Self::from_api_details`]
/// where an API is asked for its name); a name in the cxx::bridge mod, which
/// cxx spells identically in the C++ it generates
/// ([`Self::from_cxxbridge_name`]); a name autocxx built for C++ out of a
/// [`QualifiedName`] ([`Self::from_fully_qualified_name_for_subclass`]); and
/// the name of a function autocxx synthesized, which has no C++ original
/// ([`Self::from_function_without_a_reported_cpp_name`]).
#[derive(PartialEq, PartialOrd, Eq, Hash, Clone, Debug)]
pub struct CppEffectiveName(pub(crate) String);
impl CppEffectiveName {
    /// The name to use in C++ for an API: the original name bindgen reported
    /// for it, falling back on the final segment of the name autocxx knows the
    /// API by.
    ///
    /// The fallback is not reached at all across the integration suite, which
    /// is what bindgen's thoroughness about original names predicts. Reaching
    /// it takes an API autocxx synthesized, or an item which is itself
    /// anonymous or enclosed by an anonymous type, that being the one thing
    /// bindgen reports no name for; and every caller asks about a type or
    /// about a method, a method always having a name reported for it. So the
    /// segment a caller would get - the identifier for a type, the cxx::bridge
    /// name for a function - stays hypothetical. `conversion_tests` is where
    /// it does not: converting a hand-written bindgen mod records no callback
    /// results at all, so every item there falls back on its identifier, which
    /// is the name such a mod stands for C++ using.
    fn from_api_details(original_name: &Option<CppOriginalName>, api_name: &QualifiedName) -> Self {
        match original_name {
            Some(original_name) => original_name.to_effective_name(),
            None => Self(api_name.get_final_item().to_string()),
        }
    }

    fn to_string_for_cpp_generation(&self) -> &str {
        &self.0
    }

    /// The C++ name of a function declared in the cxx::bridge mod, which is
    /// simply the name it has there: cxx spells a bridge entry the same way in
    /// the C++ it generates unless asked for a `#[cxx_name]`, and neither
    /// caller asks.
    ///
    /// One caller names the `extern "Rust"` function a subclass's C++ peer
    /// calls to reach the Rust implementation of an overridden method. The
    /// other hands a generated C++ wrapper its own bridge name, for want of an
    /// original C++ name that bindgen never reported.
    fn from_cxxbridge_name(cxxbridge_name: &str) -> CppEffectiveName {
        Self(cxxbridge_name.to_string())
    }

    /// The C++ name of a function for which bindgen reported none, which is
    /// the name autocxx knows it by. See
    /// [`CppOriginalName::from_function_without_a_reported_cpp_name`], which
    /// this mirrors, for why such a function has no C++ original and what the
    /// assertion is for.
    fn from_function_without_a_reported_cpp_name(name: &str) -> CppEffectiveName {
        debug_assert!(
            !name.contains("::"),
            "`{name}` is qualified, so it is a C++ spelling from somewhere and not a name autocxx gave a function of its own"
        );
        Self(name.to_string())
    }

    fn from_fully_qualified_name_for_subclass(to_cpp_name: &str) -> CppEffectiveName {
        Self(to_cpp_name.to_string())
    }

    fn final_segment_if_any(&self) -> Option<&str> {
        self.0.rsplit_once("::").map(|(_, suffix)| suffix)
    }

    fn is_nested(&self) -> bool {
        self.0.contains("::")
    }
}

/// Confirm that each item which the user explicitly asked us to generate
/// still exists after all the analysis phases have run.
///
/// [`ParseBindgen::confirm_all_generate_directives_obeyed`] does the same job
/// at the end of the parse phase, but items which parse happily can still be
/// discarded later on, for instance because their name isn't acceptable to
/// cxx or because they depend on something we couldn't generate. Such items
/// normally become an [`Api::IgnoredItem`], which results in nothing but a
/// documentation stub in the generated code - so without this check, an
/// explicit `generate!` can appear to succeed yet produce no usable API.
///
/// This applies only to items named explicitly with `generate!` or
/// `generate_pod!`: `generate_ns!` and `generate_all!` sweep up whatever
/// they can find, and must remain tolerant of items we can't handle.
fn confirm_all_generate_directives_still_obeyed(
    config: &IncludeCppConfig,
    apis: &ApiVec<FnPhase>,
) -> Result<(), ConvertErrorFromCpp> {
    let nested_cpp_names = NestedCppNames::new(config, apis.iter().map(|api| api.name_info()));
    let mut generated: HashSet<String> = HashSet::new();
    let mut discarded: HashMap<String, &ConvertErrorFromCpp> = HashMap::new();
    for api in apis.iter() {
        match api {
            Api::IgnoredItem { err, .. } => {
                for name in api.allowlist_names(&nested_cpp_names) {
                    discarded.entry(name).or_insert(err);
                }
            }
            _ => generated.extend(api.allowlist_names(&nested_cpp_names)),
        }
    }
    for generate_directive in config.must_generate_list() {
        if !generated.contains(&generate_directive) {
            return Err(match discarded.get(&generate_directive) {
                Some(err) => ConvertErrorFromCpp::DidNotGenerateAnythingUsable(
                    generate_directive,
                    Box::new((*err).clone()),
                ),
                None => ConvertErrorFromCpp::DidNotGenerateAnything(generate_directive),
            });
        }
    }
    Ok(())
}

/// Some attributes indicate we can never handle a given item. Check for those.
fn check_for_fatal_attrs(
    callback_results: &ParseCallbackResults,
    name: &QualifiedName,
) -> Result<(), ConvertErrorWithContext> {
    if is_std_function(name) {
        // Checked before the general template-parameter case below, which is
        // how MSVC's std::function arrives here: its standard library spells
        // the type as a partial specialization over a function type, which
        // bindgen keeps as a named class whose template parameter it has
        // discarded. "One of the template parameters was incomprehensible"
        // is true but tells the user nothing about the type they wrote, and
        // the name is right here to be read. (libstdc++ and libc++ never
        // reach this: they hide std::function behind reserved
        // implementation-detail names, so bindgen erases the whole thing to
        // an opaque blob and `InvalidIdentError::BindgenOpaqueType` speaks
        // for it instead.)
        Err(ConvertErrorWithContext(
            ConvertErrorFromCpp::UnsupportedStdFunction,
            Some(ErrorContext::new_for_item(name.get_final_ident())),
        ))
    } else if callback_results.discards_template_param(name) {
        Err(ConvertErrorWithContext(
            ConvertErrorFromCpp::UnusedTemplateParam,
            Some(ErrorContext::new_for_item(name.get_final_ident())),
        ))
    } else if !matches!(
        callback_results.get_cpp_visibility(name),
        CppVisibility::Public
    ) {
        Err(ConvertErrorWithContext(
            ConvertErrorFromCpp::NonPublicNestedType,
            Some(ErrorContext::new_for_item(name.get_final_ident())),
        ))
    } else {
        Ok(())
    }
}
