// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// https://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or https://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

use autocxx_parser::{IncludeCppConfig, MultiBindings};
use proc_macro2::TokenStream;

/// Opaque structure representing the Rust which needs to be generated
/// for a given `include_cpp!` macro. You will want to pass this into
/// either [`generate_rs_single`] or [`generate_rs_archive`].
pub struct RsOutput<'a> {
    pub(crate) config: &'a IncludeCppConfig,
    pub(crate) rs: TokenStream,
}

/// Creates an on-disk archive (actually a JSON file) of the Rust side of the bindings
/// for multiple `include_cpp` macros. If you use this, you will want to tell
/// `autocxx_macro` how to find this file using the `AUTOCXX_RS_JSON_ARCHIVE`
/// environment variable.
pub fn generate_rs_archive<'a>(rs_outputs: impl Iterator<Item = RsOutput<'a>>) -> String {
    let mut multi_bindings = MultiBindings::default();
    for rs in rs_outputs {
        multi_bindings.insert(rs.config, rs.rs);
    }
    serde_json::to_string(&multi_bindings).expect("Unable to encode JSON archive")
}

/// A single Rust file to be written to disk.
pub struct RsInclude {
    pub code: String,
    pub filename: String,
}

/// Header comment placed at the top of every Rust file we write.
///
/// The generated mod already carries `#[doc = "@generated"]`, but that is an
/// attribute rather than a comment, and it says nothing about which autocxx
/// produced the file.
///
/// The token is honoured by tools which look for it: `rustfmt` skips a file
/// when any of its first five lines contains an `@generated` comment marker
/// (its `format_generated_files` option), as do Meta's code review tooling and
/// others which adopted the same convention. It is not universal - GitHub, for
/// one, decides what is generated from `linguist-generated` in
/// `.gitattributes` and has no `@generated` rule for Rust - so this marks the
/// file for the tools that read it and says which autocxx wrote it for
/// everyone else.
///
/// The marker deliberately carries no timestamp and no input path, so that
/// running autocxx twice over unchanged input produces byte-identical output.
/// Build systems which cache on file contents (Bazel, for instance) would
/// otherwise rebuild - and relink, and retest - every time the generator ran.
/// See <https://github.com/google/autocxx/issues/888>.
const GENERATED_MARKER: &str = concat!(
    "// @generated by autocxx version ",
    env!("CARGO_PKG_VERSION"),
    ". Do not edit; your changes will be overwritten on the next build.\n"
);

/// Gets the Rust code corresponding to a single [`RsOutput`]. You can write this
/// to a file which can simply be `include!`ed by `autocxx_macro` when you give
/// it the `AUTOCXX_RS_FILE` environment variable.
pub fn generate_rs_single(rs_output: RsOutput) -> RsInclude {
    RsInclude {
        code: format!("{}{}", GENERATED_MARKER, rs_output.rs),
        filename: rs_output.config.get_rs_filename(),
    }
}
